version: "3.8"

services:
  backend:
    image: ${ECR_REGISTRY}/tetris-game:backend-${IMAGE_TAG}
    ports:
      - "3000:3000"
    volumes:
      - ./server/ranks.db:/app/ranks.db
    restart: always

  frontend:
    image: ${ECR_REGISTRY}/tetris-game:frontend-${IMAGE_TAG}
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
