version: "3.8"

services:
  backend:
    image: ${ECR_REGISTRY}/tetris-game:backend-${IMAGE_TAG}
    ports:
      - "3000:3000"
    volumes:
      - ./server/ranks.db:/app/ranks.db
    restart: always
    mem_limit: 512m
    environment:
      - NODE_OPTIONS=--max-old-space-size=256

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ${ECR_REGISTRY}/tetris-game:frontend-${IMAGE_TAG}
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

    mem_limit: 128m

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
